# Generated by Django 4.2.2 on 2023-06-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gendre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='gendre',
            new_name='genre',
        ),
    ]
